api:
  environment:  "development"
  host: "192.168.1.104"
  port: 8080
  debug: true
database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "jktinfokostdb_dev"
jwt:
  secret: "8*3QdJRyDqaW=ByuXDU+TbC"
MySQLStore:
  secret: "mwRvB#E+65MpdPU3v%j8#?p"